---
paths:
  parquets: 'data/parquet/'
  pkls: 'data/pkls/'
  models: 'data/models'

files:
  companies_feat: 'companies_feat_2.parquet'
  processed_dataset: 'processed_dataset_classification_2.pkl'
  num_scaler: 'num_scaler_2.pkl'
  cat_enc: 'cat_enc_2.pkl'
  metrics: 'metrics_classification_2.pkl'
  log_reg_model: 'log_reg_2.pkl'
  rf_classifier_model: 'rf_classifier_2.pkl'
  xgb_classifier_model: 'xgb_classifier_2.pkl'

enable_optimization: False

classifiers:
  xgboost:
    default_params:
      n_estimators: 250
      learning_rate: 0.1
      max_depth: 9
      subsample: 0.6
      colsample_bytree: 0.7
    grid_params:
      n_estimators: [50, 100, 150, 200, 250]
      learning_rate: [0.001, 0.01, 0.05, 0.1, 0.2]
      max_depth: [3, 5, 7, 9, 11]
      subsample: [0.6, 0.7, 0.8, 0.9, 1.0]
      colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0]
  rf:
    default_params:
        n_estimators: 100
        max_depth: 20
        min_samples_split: 10
        min_samples_leaf: 2
        bootstrap: True
    grid_params:
      n_estimators: [50, 100, 150, 200, 250]
      max_depth: [5, 10, 15, 20]
      min_samples_split: [2, 5, 10, 15, 20]
      min_samples_leaf: [1, 2, 4, 6, 8]
      bootstrap: [True, False]
  log_reg:
    default_params:
      penalty: 'l1'
      C: 0.1
      solver: 'saga'
      max_iter: 200
    grid_params:
      penalty: ['l1', 'l2', 'elasticnet', 'none']
      C: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]
      solver: ['lbfgs', 'saga']
      max_iter: [50, 100, 200]
