---
paths:
  parquets: 'data/parquet/'
  pkls: 'data/pkls/'
  models: 'data/models'

files:
  companies_feat: 'companies_feat.parquet'
  metrics: 'metrics_classification.pkl'
  log_reg_model: 'log_reg.pkl'
  rf_classifier_model: 'rf_classifier.pkl'
  xgb_classifier_model: 'xgb_classifier.pkl'

enable_optimization: False

classifiers:

  xgboost:
    default_params:
      n_estimators: 100
      learning_rate: 0.01
      max_depth: 5
      subsample: 0.8
      colsample_bytree: 0.8
    grid_params:
      n_estimators: [50, 100, 150]
      learning_rate: [0.001, 0.01, 0.1]
      max_depth: [3, 5, 7]
      subsample: [0.8, 0.9, 1.0]
      colsample_bytree: [0.8, 0.9, 1.0]
  
  rf:
    default_params:
        n_estimators: 100
        max_depth: 5
        min_samples_split: 5
        min_samples_leaf: 2
        bootstrap: True
    grid_params:
      n_estimators: [50, 100, 150]
      max_depth: [5, 10, 15]
      min_samples_split: [2, 5, 10]
      min_samples_leaf: [1, 2, 4]
      bootstrap: [True, False]

  log_reg:
    default_params:
      penalty: 'l2'
      C: 1.0
      solver: 'lbfgs'
      max_iter: 100
    grid_params:
      penalty: ['l1', 'l2', 'elasticnet', 'none']
      C: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]
      solver: ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
      max_iter: [50, 100, 200]
