---
paths:
    egrul: 'data_raw/egrul/'
    msp: 'data_raw/msp/'
    features_region: 'data_raw/rosstat'
    features_extra: 'data_raw/msp_xml'
    parquets: 'data/parquet/'
    data: 'data/'

files:
    file_egrul: 'companies_egrul.parquet'
    file_msp: 'companies_msp.parquet'
    companies: 'companies.parquet'
    companies_feat: 'companies_feat_1.parquet'
    regions: 'regions.parquet'
    features: 'features.xlsx'
    extra_features: 'extra_features.parquet'

foundation_start: 2000
foundation_end: 2022