---
predict_by_ogrn: false
run_regression: false
run_classification: true
save_results: true

paths:
  parquets: 'data/parquet/'
  pkls: 'data/pkls/'
  models: 'data/models'
  resutls: 'results'

files:
  companies_feat: 'companies_feat_open.parquet'
  num_scaler: 'num_scaler_classification_first_year.pkl'
  cat_enc: 'cat_enc_classification_first_year.pkl'
  column_order: 'column_order_classification_first_year.pkl'
  column_order_regression: 'column_order_regression_first_year.pkl'
  regression_model: 'xgb_regressor_first_year.pkl'
  classification_model: 'xgb_classifier_3_first_year.pkl'
  df_prediction: 'predicts.parquet'