---
predict_by_ogrn: false
run_regression: true
run_classification: false
save_results: true
estimate_metrics: true

paths:
  parquets: 'data/parquet/'
  pkls: 'data/pkls/'
  models: 'data/models'
  resutls: 'results'

files:
  companies_feat: 'companies_feat_open.parquet'
  num_scaler: null #'num_scaler_classification_first_year.pkl'
  cat_enc: null #'cat_enc_classification_first_year.pkl'
  column_order: 'column_order_classification_first_year.pkl'
  column_order_regression: 'column_order_regression_first_year.pkl'
  classification_model: 'xgb_classifier_first_year.pkl'
  regression_model: 'ridge.pkl'
  df_prediction: 'predicts.pkl'