---
predict_by_ogrn: true
run_regression: false
run_classification: true
save_results: false

paths:
  parquets: 'data/parquet/'
  pkls: 'data/pkls/'
  models: 'data/models'
  resutls: 'results'

files:
  companies_feat: 'companies_feat_open.parquet'
  data_manager: 'data_manager_classification_first_year.pkl'
  regression_model: 'xgb_regressor_first_year.pkl'
  classification_model: 'xgb_classifier_3_first_year.pkl'
  df_prediction: 'predicts.parquet'