---
paths:
  parquets: 'data/parquet/'
  models: 'data/models'

test:
  categories: 
    - 0
    - 12
    - 24
    - 48
    - 120
  metrics: 'metrics_differentiated.parquet'


files:
  companies_feat: 'companies_feat_2.parquet'
  metrics: 'metrics_2.parquet'
  lr_model: 'lr.pkl'
  ridge_model: 'ridge.pkl'
  xgb_model: 'xgb.pkl'

xgboost:
  subsample: 1.0
  reg_lambda: 0.5
  reg_alpha: 0
  n_estimators: 200
  min_child_weight: 5
  max_depth: 7
  learning_rate: 0.2
  gamma: 0.5
  colsample_bytree: 0

catboost:
  random_strength: 0.1
  learning_rate: 0.1
  l2_leaf_reg: 1
  iterations: 200
  depth: 8
  bagging_temperature: 1

linear_regression:
  fit_intercept: True

ridge_regression:
  solver: 'sparse_cg'
  alpha: 1
