---
run_regression: false
run_classification: true
use_mean_for_region_features: false
enable_optimization: true

paths:
  parquets: 'data/parquet/'
  pkls: 'data/pkls/'
  models: 'data/models'

files:
  companies_feat: 'companies_feat.parquet'
  processed_dataset: 'processed_dataset.pkl'
  num_scaler: 'num_scaler_3.pkl'
  cat_enc: 'cat_encoder_3.pkl'
  metrics: 'metrics_3.parquet'
  column_order: 'column_order_3.pkl'
  log_reg_model: 'log_reg_3.pkl'
  rf_classifier_model: 'rf_classifier_3.pkl'
  xgb_classifier_model: 'xgb_classifier_3.pkl'
  lr_model: 'lr.pkl'
  ridge_model: 'ridge.pkl'
  xgb_regressor_model: 'xgb_regressor.pkl'
  catboost_regressor_model: 'catboost_regressor.pkl'

test:
  categories: 
    - 0
    - 12
    - 24
    - 48
    - 120
  metrics: 'metrics_differentiated.parquet'

regressors:
  catboost:
    default_params:
      learning_rate: 0.1
      depth: 8
      l2_leaf_reg: 1
      iterations: 200
      bagging_temperature: 1
    grid_params:
      learning_rate: [0.001, 0.01, 0.05, 0.1, 0.2]
      depth: [4, 6, 8, 10]
      l2_leaf_reg: [1, 3, 5, 7, 9]
      iterations: [100, 200, 300]
      bagging_temperature: [0, 0.5, 1, 2]
  linear_regression:
    default_params:
      fit_intercept: True
    grid_params:
      fit_intercept: [True, False]
  ridge_regression:
    default_params:
      alpha: 1
    grid_params:
      alpha: [0.1, 0.5, 1, 5, 10, 20]
  xgboost:
    default_params:
      n_estimators: 200
      learning_rate: 0.2
      max_depth: 7
      subsample: 1.0
      colsample_bytree: 0
      gamma: 0.5
      min_child_weight: 5
      reg_lambda: 0.5
      reg_alpha: 0
    grid_params:
      n_estimators: [50, 100, 150, 200, 250]
      learning_rate: [0.001, 0.01, 0.05, 0.1, 0.2]
      max_depth: [3, 5, 7, 9, 11]
      subsample: [0.6, 0.7, 0.8, 0.9, 1.0]
      colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0]
      gamma: [0, 0.1, 0.2, 0.5, 1]
      min_child_weight: [1, 3, 5, 7]
      reg_lambda: [0.01, 0.1, 1, 10, 100]
      reg_alpha: [0.01, 0.1, 1, 10, 100]

classifiers:
  xgboost:
    default_params:
      n_estimators: 250
      learning_rate: 0.1
      max_depth: 9
      subsample: 0.6
      colsample_bytree: 0.7
      gamma: 0
      min_child_weight: 1
    grid_params:
      n_estimators: [50, 100, 150, 200, 250]
      learning_rate: [0.001, 0.01, 0.05, 0.1, 0.2]
      max_depth: [3, 5, 7, 9, 11]
      subsample: [0.6, 0.7, 0.8, 0.9, 1.0]
      colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0]
      gamma: [0, 0.1, 0.2, 0.5, 1]
      min_child_weight: [1, 3, 5, 7]
  rf:
    default_params:
        n_estimators: 100
        max_depth: 20
        min_samples_split: 10
        min_samples_leaf: 2
        bootstrap: True
    grid_params:
      n_estimators: [50, 100, 150, 200, 250]
      max_depth: [5, 10, 15, 20]
      min_samples_split: [2, 5, 10, 15, 20]
      min_samples_leaf: [1, 2, 4, 6, 8]
      bootstrap: [True, False]
  log_reg:
    default_params:
      penalty: 'l1'
      C: 0.1
      solver: 'saga'
      max_iter: 200
    grid_params:
      penalty: ['l1', 'l2', 'elasticnet', 'none']
      C: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0]
      solver: ['lbfgs', 'saga']
      max_iter: [50, 100, 200]